### ISSUE TITLE
fix: center the card on the home page vertically

### ISSUE THREAD

**Issue by gretmn102** [gretmn102/gretmn102.github.io#1]
Суть вот в чем: карточка выровнена по вертикали сейчас с помощью обертки с таким правилом:

```css
.card-wrapper {
  height: 100vh;

  display: flex;
  align-items: center;
  justify-content: center;
}
```

И в итоге получается такое:

![изображение](https://github.com/gretmn102/gretmn102.github.io/assets/14349457/ad47432e-a501-465a-9bb1-60b736eb8b01)

И выровнять всё это дело мешает navbar.

### Сделать navbar fixed

Для этого достаточно добавить в `src/css/custom.css` следующее правило:

```css
.navbar {
  position: fixed;
  width: 100%;
}
```

Но оно распространяется глобально, и на всех остальных страницах получается что-то такое:

![изображение](https://github.com/gretmn102/gretmn102.github.io/assets/14349457/6082ad9b-1ad4-4e12-8b98-eb977d502194)

### Поднять обертку с помощью хардкода

Navbar занимает `60px`, значит, подымаем ее настолько:

```css
.card-wrapper {
  position: relative;
  top: -60px;
  height: 100vh;

  display: flex;
  align-items: center;
  justify-content: center;
}
```

Работает хорошо, но как и любого хардкода есть проблема в хардкоде, ага: высота navbar изменится — всё поломается.
